In [174]:
#setup
import bs4 as bs
import urllib.request
import pandas as pd
SDG_Cat = []
SDG_Num = []
year = []
var_names = []
val_val = []
dic = {}
df = pd.DataFrame(columns = ['SDG_Category', 'SDG_Number', 'Year', 'Variable_Name', 'Variable_Value'])
address = 'https://sdg.data.gov/'
site = urllib.request.urlopen(address).read()
lxml = bs.BeautifulSoup(site, 'lxml')

#making a list of all the initial urls
links = []
links2 = []
for url in lxml.find_all('a'):
    links.append((url.get('href')))
del links[0:6]
links.remove("#")
links = [x[2:] for x in links]

for page in links:
    stor = []
    temp3 = ""
    lst = urllib.request.urlopen(address+page).read()
    lst = bs.BeautifulSoup(lst, 'lxml')
    for url in lst.find_all('a'):
        stor.append(url.get("href"))
    del stor[0:7]
    stor.remove("#")
    links2.extend(stor)
    
#making dict for number to category
    
    stor = [x[1:] for x in stor]
    temp3 = str(page[:-1])
    stor = stor[0]
    dic[stor[0:2]] = temp3
    
    
#take slash off links

links2 = [x[1:] for x in links2]

#Grab all cvs from cite

for item in links2:
    temp2 = []
    address2 = address+"data/indicator_"+item+'.csv'
    csvs = pd.read_csv(address2)
    year_lp = csvs.iloc[:,0]
    csvs = csvs.iloc[:,1:]
    var_names_lp = list(csvs)
    csvs = csvs.T
#add data to final chart

    val_val_lp = []
    #print(csvs)
# for each column in teh dataframe grabs data to list and then adds lists togther

    for column in csvs:
        lst2 = csvs.iloc[:,column]
        val_val_lp.extend(list(lst2))
    count = int(len(val_val_lp)/len(var_names_lp)) 
    var_names_lp = var_names_lp * (count)


#add var name data and val val data to chart
    
    var_names.extend(var_names_lp)
    val_val.extend(val_val_lp)
    year_lp = list(year_lp)
    count = int(len(val_val_lp)/len(year_lp))
    year_temp = []
    
#dulpicating years correctly
    
    for x in year_lp:
        temp = []
        temp.append(x)
        temp = temp * count
        year_temp.extend(temp)
        year_lp = year_temp
    year.extend(year_lp)
    
#adding the file number used    
    
    temp2.append(item)
    temp2 = temp2 * int(len(val_val_lp))
    SDG_Num.extend(temp2)
    
# final category setup
for key in SDG_Num:
    SDG_Cat.append(dic[key[0:2]])
    
# final chart construction

from IPython.display import display, HTML
df1 = pd.DataFrame({'SDG_Category': SDG_Cat})
df1 = df1.assign(SDG_Number=pd.Series(SDG_Num))
df1 = df1.assign(Year=pd.Series(year))
df1 = df1.assign(Variable=pd.Series(var_names))
df1 = df1.assign(Value=pd.Series(val_val))
pd.set_option('display.max_columns', None)  
display(df1)

,SDG_Category,SDG_Number,Year,Variable,Value
0,no-poverty,1-1-1,2015,var_1,0
1,no-poverty,1-1-1,2015,var_2,0
2,no-poverty,1-2-1,2007,tot_proportion_belownatpov_line,NaN
3,no-poverty,1-2-1,2007,male,NaN
4,no-poverty,1-2-1,2007,female,NaN
5,no-poverty,1-2-1,2007,under_18_years,NaN
6,no-poverty,1-2-1,2007,18_64_years,NaN
7,no-poverty,1-2-1,2007,65andover_years,NaN
8,no-poverty,1-2-1,2007,Note,NaN
9,no-poverty,1-2-1,2008,tot_proportion_belownatpov_line,NaN
10,no-poverty,1-2-1,2008,male,NaN
11,no-poverty,1-2-1,2008,female,NaN
12,no-poverty,1-2-1,2008,under_18_years,NaN
13,no-poverty,1-2-1,2008,18_64_years,NaN
14,no-poverty,1-2-1,2008,65andover_years,NaN
15,no-poverty,1-2-1,2008,Note,NaN
16,no-poverty,1-2-1,2009,tot_proportion_belownatpov_line,NaN
17,no-poverty,1-2-1,2009,male,NaN
18,no-poverty,1-2-1,2009,female,NaN
19,no-poverty,1-2-1,2009,under_18_years,NaN
20,no-poverty,1-2-1,2009,18_64_years,NaN
21,no-poverty,1-2-1,2009,65andover_years,NaN
22,no-poverty,1-2-1,2009,Note,NaN
23,no-poverty,1-2-1,2010,tot_proportion_belownatpov_line,NaN
24,no-poverty,1-2-1,2010,male,NaN
25,no-poverty,1-2-1,2010,female,NaN
26,no-poverty,1-2-1,2010,under_18_years,NaN
27,no-poverty,1-2-1,2010,18_64_years,NaN
28,no-poverty,1-2-1,2010,65andover_years,NaN
29,no-poverty,1-2-1,2010,Note,NaN
...,...,...,...,...,...
5866,partnerships-for-the-goals,17-18-3,2015,funding1,National government
5867,partnerships-for-the-goals,17-19-1,2015,var_1,0
5868,partnerships-for-the-goals,17-19-1,2015,var_2,0
5869,partnerships-for-the-goals,17-19-2,2007,house_census,yes
5870,partnerships-for-the-goals,17-19-2,2007,100_pct_birthreg,yes
5871,partnerships-for-the-goals,17-19-2,2007,80_pct_deathreg,yes
5872,partnerships-for-the-goals,17-19-2,2008,house_census,yes
5873,partnerships-for-the-goals,17-19-2,2008,100_pct_birthreg,yes
5874,partnerships-for-the-goals,17-19-2,2008,80_pct_deathreg,yes
5875,partnerships-for-the-goals,17-19-2,2009,house_census,yes
5876,partnerships-for-the-goals,17-19-2,2009,100_pct_birthreg,yes
5877,partnerships-for-the-goals,17-19-2,2009,80_pct_deathreg,yes
5878,partnerships-for-the-goals,17-19-2,2010,house_census,yes
5879,partnerships-for-the-goals,17-19-2,2010,100_pct_birthreg,yes
5880,partnerships-for-the-goals,17-19-2,2010,80_pct_deathreg,yes
5881,partnerships-for-the-goals,17-19-2,2011,house_census,yes
5882,partnerships-for-the-goals,17-19-2,2011,100_pct_birthreg,yes
5883,partnerships-for-the-goals,17-19-2,2011,80_pct_deathreg,yes
5884,partnerships-for-the-goals,17-19-2,2012,house_census,yes
5885,partnerships-for-the-goals,17-19-2,2012,100_pct_birthreg,yes
5886,partnerships-for-the-goals,17-19-2,2012,80_pct_deathreg,yes
5887,partnerships-for-the-goals,17-19-2,2013,house_census,yes
5888,partnerships-for-the-goals,17-19-2,2013,100_pct_birthreg,yes
5889,partnerships-for-the-goals,17-19-2,2013,80_pct_deathreg,yes
5890,partnerships-for-the-goals,17-19-2,2014,house_census,yes
5891,partnerships-for-the-goals,17-19-2,2014,100_pct_birthreg,yes
5892,partnerships-for-the-goals,17-19-2,2014,80_pct_deathreg,yes
5893,partnerships-for-the-goals,17-19-2,2015,house_census,yes
5894,partnerships-for-the-goals,17-19-2,2015,100_pct_birthreg,yes
5895,partnerships-for-the-goals,17-19-2,2015,80_pct_deathreg,yes