Setup

In [1]:
import nltk 
import pandas as pd
from nltk.tokenize import RegexpTokenizer
df = pd.read_csv("Project5_data.csv")

"""optional addition for testing so that teh code doesnt take 20 minutes to run

df = df.head(10) #number of rows you want to use

there are over 160000 rows so"""

df = df.iloc[:,0]
word_count = []
char_count = []
noun = []
verb = []
adj = []
other = []

The main function

In [2]:
# loop through each complaint
for item in df:
    word_lst = []
    char_lst = 0
    count = 0
    count_n = 0
    count_v = 0
    count_a = 0
    count_o = 0
    
    #divide into words and remove puntion
    
    tokenizer = RegexpTokenizer(r'\w+')
    item = tokenizer.tokenize(item)
    
    #tag each word with its part of speach
        
    tagged = nltk.pos_tag(item,tagset='universal')
    tagged = [x[1] for x in tagged]
   
    #separate by part of speach

    for y in tagged:

        if (y == 'NOUN'):
            count_n += 1
        elif (y == 'VERB'):
            count_v += 1
        elif (y == 'ADJ'):
            count_a += 1
        else:
            count_o += 1
            
     #add to teh list to be added fed into teh dataframe       
            
    noun.append(str(count_n))
    verb.append(str(count_v))
    adj.append(str(count_a))
    other.append(str(count_o))
    
    #find unique words and number of characters
              
    for word in item:
        word = word.lower()
        char_lst += len(word)
        if (word not in word_lst):
            word_lst.append(word)
            count += 1
    word_count.append(count)
    char_count.append(char_lst)

Set up dataframe

In [3]:
from IPython.display import display, HTML
df1 = pd.DataFrame({'Unique_Words': word_count})
df1 = df1.assign(Character_Count=pd.Series(char_count))
df1 = df1.assign(Nouns=pd.Series(noun))
df1 = df1.assign(Verbs=pd.Series(verb))
df1 = df1.assign(Adjectives=pd.Series(adj))
df1 = df1.assign(Others=pd.Series(other))
pd.set_option('display.max_columns', None)  
display(df1)

   Unique_Words  Character_Count Nouns Verbs Adjectives Others
0            78              557    41    19          9     49
1           230             2705   134   157         30    307
2            72              425    18    26          5     55
3           123             1083    76    53         19     85
4           139             1138    69    74         10    135
5           109              973    59    51          9     89
6            69              466    32    23          4     52
7           105              821    60    30         12     90
8            46              269    15    17          0     29
9            77              493    27    29          1     56